backend:
  name: git-gateway
  branch: main
locale: fr
media_folder: 'assets/uploads'
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: guidelines
    label: Recommandations
    folder: _guidelines
    extension: html
    create: true
    editor:
      preview: false
    fields:
      - label: Numéro
        name: number
      - label: Titre
        name: title
      - label: Texte
        name: text
        widget: markdown
        minimal: true
        required: false
        buttons: [bold, link, bulleted-list]
        editor_components: []
        modes: [rich_text]
      - label: "Thèmes"
        name: "themes"
        widget: "relation"
        collection: "themes"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
  - name: themes
    label: Thèmes
    folder: _themes
    extension: html
    create: true
    editor:
      preview: false
    fields:
      - label: Titre
        name: title
